### ISSUE TITLE
Hide meter until user starts typing

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#11]
Could the password strength indicator (the pink bar next to the grey padlock) only become visible if a user starts typing in one of the password boxes?

The current default behaviour looks like a user has a weak password with nothing in the password fields, even though they may have a strong or better current password.

**Comment by seethroughdev** [comment]
Yeah, I see what you mean.  I'll fix that up when I can put together an update.

**Comment by binarykitchen** [comment]
great, thanks - hopefully soon :)

**Comment by seethroughdev** [comment]
This is fixed.  Will push to bump and push version to npm tomorrow!

**Comment by seethroughdev** [comment]
updated to 0.9.5 in npm.

https://www.npmjs.com/package/react-ux-password-field

**Comment by binarykitchen** [comment]
thx  man
