### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#14]
I see the above warning sometimes. Can you check pls?

**Comment by seethroughdev** [comment]
Still getting this error @binarykitchen?  Or okay to close.

**Comment by binarykitchen** [comment]
nope, all good now i think

**Comment by binarykitchen** [comment]
Opened as a new issue in https://github.com/seethroughtrees/react-ux-password-field/issues/25
