### ISSUE TITLE
option needed: unMaskStyle

### ISSUE THREAD

**Issue by weisjohn** [seethroughtrees/react-ux-password-field#21]
There doesn't seem to be a way to override the font-italic, etc of `unMaskStyle`...
https://github.com/seethroughtrees/react-ux-password-field/blob/master/src/index.js#L68

**Comment by seethroughdev** [comment]
Ugh, yeah, that shouldn't be like that.  I'll fix it up and push a new version.  Keep you updated.

**Comment by seethroughdev** [comment]
Removed and updated in https://github.com/seethroughtrees/react-ux-password-field/releases/tag/0.9.8

Thanks!
