### ISSUE TITLE
Do not call addPasswordType() when umounted

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#25]
This is a delayed call from the debounce logic which can trigger following React warning:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
```

I recommend not to execute anything in the debounce when unmounted.

**Comment by binarykitchen** [comment]
PS: use `componentWillUnmount()` for the fix

**Comment by binarykitchen** [comment]
ping?

**Comment by seethroughdev** [comment]
Sure.  Makes sense.  If you'd like to submit a PR with the change in the src/ folder, I can compile and deploy.  

Thanks.

**Comment by binarykitchen** [comment]
here you go ... happy with that?

**Comment by seethroughdev** [comment]
Yep, works for me...  Do you want collaborator access for this repo?

**Comment by binarykitchen** [comment]
me? thanks for the offer but i doubt i will contribute much. this was just one-off occasion.

**Comment by seethroughdev** [comment]
np.  I'll try and get it up tonight...  Keep you updated.

**Comment by binarykitchen** [comment]
any news?

**Comment by seethroughdev** [comment]
I updated and bumped version with npm.  Let me know if you have any issues...

**Comment by binarykitchen** [comment]
no, works very well now. all good, thx for cooperating
