### ISSUE TITLE
When 'handleChange' is called the wrong 'isValid' value is sent to parent component

### ISSUE THREAD

**Issue by wesleycyu** [seethroughtrees/react-ux-password-field#28]
I have a password reset component that uses this library, but I'm running into an issue where the parent component receives the wrong `isValid` property when `handleChange` is called.

It seems to be because the `setState` calls from `handleZxcvbn` and `handleMinLength` that set `isValid` are not synchronous so the value passed to the parent is always one behind the updated value.

**Comment by seethroughdev** [comment]
Hi @wesleycyu .  So sorry I never saw this.  I don't actively use this component, but I know there are a few people who do.  Were you able to fix?  If so, any chance of submitting a PR?  

Thanks.

**Comment by wesleycyu** [comment]
@seethroughtrees I ended up fixing it using the parent component. If I find some time in the next few weeks, I'll make a PR for the component itself :)

**Comment by seethroughdev** [comment]
That would be great.  Thanks!
