### ISSUE TITLE
Uncaught ReferenceError: zxcvbn is not defined

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#3]
This package is very nice but I get the above error :(

This around that code:

``` js
          handleZxcvbn: function handleZxcvbn(val) {
            var stats = zxcvbn(val),
                currentScore = stats.score;
```

I think a `zxcvbn = require('zxcvbn')` is missing somewhere ...

**Comment by binarykitchen** [comment]
I think it should be added as a dependency in the package.json and required from there.

**Comment by seethroughdev** [comment]
Thanks @binarykitchen ...

Zxcvbn is quite large and has to be loaded async on the client.  That's what Dropbox recommends in their readme.  Which is why you won't find it as a module dependency.

I'm not seeing any errors in the demo.  Can you verify that the file is being loaded async in your <head> ?

**Comment by binarykitchen** [comment]
well, i work for a large security app. we cannot load external dependencies and all must work offline as well. that's why ...

**Comment by seethroughdev** [comment]
I think i wrote it so you can override the src url for the library if you wanted to load it locally.

the zxcvbn prop -- can make it false to disable or pass in a url for an alternate src.  Maybe make it point to your local..?

**Comment by binarykitchen** [comment]
yeah, done that. unfortunately zxcvbn is not on npm, see https://github.com/dropbox/zxcvbn/pull/24

**Comment by seethroughdev** [comment]
Sounds like you got it working...  

But the async code to load zxcvbn checks if the var exists.  So you can load the file before before your app and be fine, doesnt' require npm.  Or you can specify the src as a local file and download it manually or with bower.

**Comment by binarykitchen** [comment]
yes, i got it working by listing `dropbox/zxcvbn` in the package.json and `require` it from there. this will ensure the app also works offline.
