### ISSUE TITLE
dangerouslySetInnerHTML error when nesting HTML within InputPassword component

### ISSUE THREAD

**Issue by Robinnnnn** [seethroughtrees/react-ux-password-field#35]
I need to place a `<label>` block right beneath the `<input>` block for some animations to work. So far I've made it possible via the following:

```
<InputPassword className="input__field input__field--kohana password">
    <label className="input__label input__label--kohana">
        <i className={"fa fa-fw icon icon--kohana fa-lock" }></i>
        <span className="input__label-content input__label-content--kohana">Password</span>
    </label>
</InputPassword>
```

Works like a charm. However, my console complains with the following message on every keypress:
`Warning: input is a void element tag and must not have 'children' or use 'props.dangerouslySetInnerHTML'. Check the render method of InputPassword.`

How can I avoid this error?

Simply rewriting in this way does not do the trick:

```
<InputPassword className="input__field input__field--kohana password" />
<label className="input__label input__label--kohana">
    <i className={"fa fa-fw icon icon--kohana fa-lock" }></i>
    <span className="input__label-content input__label-content--kohana">Password</span>
</label>
```

**Comment by seethroughdev** [comment]
Hi @Robinnnnn .  Do you have a link to see the animation and markup?  It would be ideal to make it work without inserting the elements inside.

**Comment by seethroughdev** [comment]
*also, sorry for the delay, I'm not able to actively support this component these days, but I'm happy to help if I can.

**Comment by Robinnnnn** [comment]
I just found a different way to do this via jQuery. Thanks!
