### ISSUE TITLE
doesn't work with server side prerendering

### ISSUE THREAD

**Issue by EXC-BAD-ACCESS** [seethroughtrees/react-ux-password-field#36]
this [line](https://github.com/seethroughtrees/react-ux-password-field/blob/9200fb45fcec6fd256e1bc6a5ee4dd5442ac019e/src/index.js#L249) references "navigator" which doesn't exist on the server, it could be changed to something like: `if (typeof navigator !== 'undefined' && !/Firefox/.test(navigator.userAgent)) return;` to support server side rendering

**Comment by seethroughdev** [comment]
makes sense.  thanks @AppSorcery want to send a PR?

**Comment by EXC-BAD-ACCESS** [comment]
#37

**Comment by EXC-BAD-ACCESS** [comment]
when i tested my previous pull request i must have accidentally been running webpack's hot-dev-server which doesn't quite work the same a a deployed version of a prerendered app...

when i went to deploy i found it still wasn't working with prerendering because of the `getDOMNode()` call in the same timeout function.  #39 fixes it (and was tested in a real deployment ;)

**Comment by seethroughdev** [comment]
Hi @AppSorcery , can you take a look at the latest and make sure it solves the issue?   Thanks.
