### ISSUE TITLE
style for infoBar

### ISSUE THREAD

**Issue by Dr8g0n** [seethroughtrees/react-ux-password-field#49]
How do I pass the style for infoBar (passwordField__info)?

        <InputPassword style={styles.password}
                    id="password"
                    name="password"
                    placeholder="Enter Password"
                    minLength={7}
                    onChange={this.handlePass1}
                    value={pass1}
                />

Thanks!

**Comment by seethroughdev** [comment]
Hi @Dr8g0n , sorry for the delay.  Unfortunately, this repo is deprecated, and not ready to support future versions of React.  I'd definitely recommend trying https://github.com/mmw/react-password-strength out instead!  hopefully it has a more updated api for you as well.  Best of luck.
