### ISSUE TITLE
How to add a custom strength / score for repeated password inputs?

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#5]
I have an UI here with two password entries, the latter one asks the user to repeat the same password.

Assuming both entries do not match, I would like to add a custom message for the repeated input saying "Both passwords do not match".

How can I do this with a custom strength / score?

**Comment by seethroughdev** [comment]
Not sure I follow this one, can you send an example?

**Comment by binarykitchen** [comment]
never mind, i solved it myself the other way around. see
https://gist.github.com/binarykitchen/4786a4f68372cc34e13d

feedback welcome

**Comment by seethroughdev** [comment]
awesome.  i played a lot with situations like this, but felt it was best to keep it separate for me.  glad you were able to make it work...!
