### ISSUE TITLE
make this.props.onChange conditional

### ISSUE THREAD

**Issue by imjared** [seethroughtrees/react-ux-password-field#7]
I don't really need it but it's running whether the prop is there or not so it breaks everything :(

https://github.com/seethroughtrees/react-ux-password-field/blob/master/src/index.js#L123

**Comment by seethroughdev** [comment]
Ah, gotcha.  Let me push up a fix for that.

**Comment by seethroughdev** [comment]
I don't have time to test atm, but don't want to have your page broken.  Can you grab master and test?

https://github.com/seethroughtrees/react-ux-password-field/blob/master/src/index.js#L123

**Comment by imjared** [comment]
That's exactly what I had implemented locally and it worked like a charm :+1:

**Comment by seethroughdev** [comment]
awesome.  lemme push up to npm.

**Comment by seethroughdev** [comment]
cool.  pushed.  https://www.npmjs.com/package/react-ux-password-field/

thanks for letting me know.
