### ISSUE TITLE
Need DOM access to password input

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#9]
Could you add a public `getInputDOMNode()` in your code?

So that I can do some calls on the DOM node itself, i.E. `setCustomValidity()`

**Comment by seethroughdev** [comment]
I'm pretty swamped on a work project, atm.  but if you want to submit a PR, i'd be happy to add it in.  Just send it to the Upstream branch in the repo.  Or I'll try and get to it over the weekend or something...

**Comment by binarykitchen** [comment]
Take your time to add this in the next weeks. Thanks!

**Comment by seethroughdev** [comment]
Can you point me towards some documentation for this?  If you're referring to a ref attribute on the input it exists, and is equal to the value of this.props.id.

Let me know if that's not what you're looking for.

**Comment by seethroughdev** [comment]
Closing this.  @binarykitchen if you see any reason to reopen, let me know and we can figure it out.
